Document: sparky4-apt
Title: Debian sparky4-apt Manual
Author: <insert document author here>
Abstract: This manual describes what sparky4-apt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sparky4-apt/sparky4-apt.sgml.gz

Format: postscript
Files: /usr/share/doc/sparky4-apt/sparky4-apt.ps.gz

Format: text
Files: /usr/share/doc/sparky4-apt/sparky4-apt.text.gz

Format: HTML
Index: /usr/share/doc/sparky4-apt/html/index.html
Files: /usr/share/doc/sparky4-apt/html/*.html
