Document: sparky5-apt
Title: Debian sparky5-apt Manual
Author: <insert document author here>
Abstract: This manual describes what sparky5-apt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sparky5-apt/sparky5-apt.sgml.gz

Format: postscript
Files: /usr/share/doc/sparky5-apt/sparky5-apt.ps.gz

Format: text
Files: /usr/share/doc/sparky5-apt/sparky5-apt.text.gz

Format: HTML
Index: /usr/share/doc/sparky5-apt/html/index.html
Files: /usr/share/doc/sparky5-apt/html/*.html
