Document: sparky-apt-sb
Title: Debian sparky-apt-sb Manual
Author: <insert document author here>
Abstract: This manual describes what sparky-apt-sb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sparky-apt-sb/sparky-apt-sb.sgml.gz

Format: postscript
Files: /usr/share/doc/sparky-apt-sb/sparky-apt-sb.ps.gz

Format: text
Files: /usr/share/doc/sparky-apt-sb/sparky-apt-sb.text.gz

Format: HTML
Index: /usr/share/doc/sparky-apt-sb/html/index.html
Files: /usr/share/doc/sparky-apt-sb/html/*.html
